version: ">= 0.13"
formatter: markdown
recursive: true
sort:
  enabled: true
  by: required

content: |-
  # {{ .Header }}

  {{ .Description }}

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Resources

  {{ .Resources }}

  ## Inputs

  {{ .Inputs }}

  ## Outputs

  {{ .Outputs }}
